name: Branch Created
on:
  create:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue
        id: extract
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ISSUE_KEY=$(echo $BRANCH_NAME | grep -oP '([A-Z]+-\d+)')
          echo "Branch name: $BRANCH_NAME"
          echo "Extracted issue key: $ISSUE_KEY"
          echo "issue=$ISSUE_KEY" >> $GITHUB_OUTPUT

#      작업 ID를 확인하고 싶을 때 사용
#      - name: Get Available Transitions
#        run: |
#          curl -v -L -X GET \
#            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
#            -H "Content-Type: application/json" \
#            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions"

      - name: Update Jira Status
        run: |
          curl -v -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions \
            -d '{
              "transition": {"id": "2"},
              "fields": {
                "assignee": {"name": "${{ github.actor }}"}
              }
            }'