name: Branch Created
on:
  create:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue
        id: extract
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ISSUE_KEY=$(echo $BRANCH_NAME | grep -oP '([A-Z]+-\d+)')
          echo "issue=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Update Jira Status
        run: |
          curl -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions \
            -d '{
              "transition": {"name": "작업 중"},
              "fields": {
                "assignee": {"name": "${{ github.actor }}"}
              }
            }'