name: Spring Boot CI/CD Pipeline
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue
        id: extract
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          ISSUE_KEY=$(echo $PR_TITLE | grep -oP '([A-Z]+-\d+)')
          echo "issue=$ISSUE_KEY" >> $GITHUB_OUTPUT

      # 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Gradle 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 빌드
      - name: Build with Gradle
        id: build
        run: |
          ./gradlew clean build
          if [ $? -ne 0 ]; then
            curl -X POST \
              -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions \
              -d '{"transition": {"id": "10"}}'
            exit 1
          fi

      # 테스트
      - name: Run Tests
        run: |
          ./gradlew test
          if [ $? -ne 0 ]; then
            curl -X POST \
              -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions \
              -d '{"transition": {"id": "10"}}'
            exit 1
          fi

      # Docker 빌드 & 푸시
      - name: Build & Push Docker Image
        if: success()
        run: |
          docker build -t your-docker-image:${{ github.sha }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-docker-image:${{ github.sha }}
          if [ $? -ne 0 ]; then
            curl -X POST \
              -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions \
              -d '{"transition": {"id": "10"}}'
            exit 1
          fi

      # EC2 배포 (예시)
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull your-docker-image:${{ github.sha }}
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d --name spring-app -p 8080:8080 your-docker-image:${{ github.sha }}

      # 성공 시 작업 완료로 상태 변경
      - name: Update to Work Complete
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions \
            -d '{"transition": {"id": "8"}}'

#      # 실패 알림 (선택사항)
#      - name: Notify Error
#        if: failure()
#        run: |
#          curl -X POST -H 'Content-type: application/json' \
#            --data '{"text":"Spring 서버 빌드/배포 실패: ${{ steps.extract.outputs.issue }}"}' \
#            ${{ secrets.SLACK_WEBHOOK_URL }}