name: PR Title and Status Update
on:
  pull_request:
    types: [opened, edited, closed]

permissions:
  pull-requests: write
  contents: read

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update PR Title
        id: update-title
        run: |
          PR_BRANCH="${{ github.head_ref }}"
          echo "PR branch: $PR_BRANCH"
          
          ISSUE_KEY=$(echo $PR_BRANCH | grep -oP 'GROU-\d+')
          echo "Found issue key: $ISSUE_KEY"
          
          if [ ! -z "$ISSUE_KEY" ]; then
            CURRENT_TITLE="${{ github.event.pull_request.title }}"
            if [[ ! "$CURRENT_TITLE" =~ ^\[GROU-[0-9]+\] ]]; then
              NEW_TITLE="[$ISSUE_KEY] $CURRENT_TITLE"
              echo "Updating title to: $NEW_TITLE"
          
              curl -X PATCH \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
                -d "{\"title\":\"$NEW_TITLE\"}"
          
              echo "title=$NEW_TITLE" >> $GITHUB_OUTPUT
            else
              echo "title=$CURRENT_TITLE" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Extract Jira Issue
        id: extract
        if: success()
        run: |
          TITLE="${{ steps.update-title.outputs.title }}"
          echo "Processing title: $TITLE"
          ISSUE_KEY=$(echo $TITLE | grep -oP 'GROU-\d+')
          echo "Extracted Issue Key: $ISSUE_KEY"
          echo "issue=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Update to QA
        if: github.event.action == 'opened' && success()
        run: |
          echo "Updating issue ${{ steps.extract.outputs.issue }} to QA"
          curl -v -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.issue }}/transitions" \
            -d '{"transition": {"id": "7"}}'
